# Generated by Django 2.2.6 on 2019-10-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название города')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='ЧПУ название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название специализации')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='ЧПУ')),
                ('related', models.ManyToManyField(blank=True, related_name='related_specs', to='mainapp.Specialization', verbose_name='Подспециализации')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyername', models.CharField(max_length=255, verbose_name='ФИО')),
                ('major', models.CharField(blank=True, max_length=128, verbose_name='Специальность')),
                ('aboutself', models.TextField(blank=True, verbose_name='О себе')),
                ('exp_year', models.CharField(max_length=5, verbose_name='Стаж/Опыт')),
                ('image', models.ImageField(blank=True, upload_to='uploads/lawyers/', verbose_name='Изображение')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.City')),
                ('specializations', models.ManyToManyField(blank=True, related_name='specializations', to='mainapp.Specialization', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'Юрист',
                'verbose_name_plural': 'Юристы',
                'ordering': ['lawyername'],
            },
        ),
    ]
