# Generated by Django 2.2.6 on 2019-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_specialization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
