# Generated by Django 2.2.6 on 2019-11-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191111_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_names',
            field=models.TextField(blank=True, verbose_name='Падежи города'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор комментария')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainapp.Lawyer', verbose_name='Юрист')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['id'],
            },
        ),
    ]
