# Generated by Django 2.2.6 on 2019-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='coords',
            field=models.CharField(blank=True, max_length=128, verbose_name='Координаты'),
        ),
    ]
