# Generated by Django 2.2.6 on 2019-12-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_city_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='name_form',
            field=models.CharField(blank=True, help_text='Форма', max_length=255, verbose_name='Форма'),
        ),
    ]
