# Generated by Django 2.2.6 on 2019-12-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_specialization_name_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email', max_length=128, verbose_name='Email')),
                ('phone_number', models.CharField(help_text='Номер телефона', max_length=128, verbose_name='Номер телефона')),
                ('question', models.TextField(help_text='Вопрос', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['email'],
            },
        ),
    ]
