# Generated by Django 2.2.6 on 2020-01-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='sorting',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='Ваш вопрос', verbose_name='Вопрос'),
        ),
    ]
